INSERT INTO icd9 VALUES(1,'0010','Cholera due to vibrio cholerae');
INSERT INTO icd9 VALUES(2,'0011','Cholera due to vibrio cholerae el tor');
INSERT INTO icd9 VALUES(3,'0019','Cholera, unspecified');
INSERT INTO icd9 VALUES(4,'0020','Typhoid fever');
INSERT INTO icd9 VALUES(5,'0021','Paratyphoid fever A');
INSERT INTO icd9 VALUES(6,'0022','Paratyphoid fever B');
INSERT INTO icd9 VALUES(7,'0023','Paratyphoid fever C');
INSERT INTO icd9 VALUES(8,'0029','Paratyphoid fever, unspecified');
INSERT INTO icd9 VALUES(9,'0030','Salmonella gastroenteritis');
INSERT INTO icd9 VALUES(10,'0031','Salmonella septicemia');
INSERT INTO icd9 VALUES(11,'00320','Localized salmonella infection, unspecified');
INSERT INTO icd9 VALUES(12,'00321','Salmonella meningitis');
INSERT INTO icd9 VALUES(13,'00322','Salmonella pneumonia');
INSERT INTO icd9 VALUES(14,'00323','Salmonella arthritis');
INSERT INTO icd9 VALUES(15,'00324','Salmonella osteomyelitis');
INSERT INTO icd9 VALUES(16,'00329','Other localized salmonella infections');
INSERT INTO icd9 VALUES(17,'0038','Other specified salmonella infections');
INSERT INTO icd9 VALUES(18,'0039','Salmonella infection, unspecified');
INSERT INTO icd9 VALUES(19,'0040','Shigella dysenteriae');
INSERT INTO icd9 VALUES(20,'0041','Shigella flexneri');
INSERT INTO icd9 VALUES(21,'0042','Shigella boydii');
INSERT INTO icd9 VALUES(22,'0043','Shigella sonnei');
INSERT INTO icd9 VALUES(23,'0048','Other specified shigella infections');
INSERT INTO icd9 VALUES(24,'0049','Shigellosis, unspecified');
INSERT INTO icd9 VALUES(25,'0050','Staphylococcal food poisoning');
INSERT INTO icd9 VALUES(26,'0051','Botulism food poisoning');
INSERT INTO icd9 VALUES(27,'0052','Food poisoning due to Clostridium perfringens (C. welchii)');
INSERT INTO icd9 VALUES(28,'0053','Food poisoning due to other Clostridia');
INSERT INTO icd9 VALUES(29,'0054','Food poisoning due to Vibrio parahaemolyticus');
INSERT INTO icd9 VALUES(30,'00581','Food poisoning due to Vibrio vulnificus');
INSERT INTO icd9 VALUES(31,'00589','Other bacterial food poisoning');
INSERT INTO icd9 VALUES(32,'0059','Food poisoning, unspecified');
INSERT INTO icd9 VALUES(33,'0060','Acute amebic dysentery without mention of abscess');
INSERT INTO icd9 VALUES(34,'0061','Chronic intestinal amebiasis without mention of abscess');
INSERT INTO icd9 VALUES(35,'0062','Amebic nondysenteric colitis');
INSERT INTO icd9 VALUES(36,'0063','Amebic liver abscess');
INSERT INTO icd9 VALUES(37,'0064','Amebic lung abscess');
INSERT INTO icd9 VALUES(38,'0065','Amebic brain abscess');
INSERT INTO icd9 VALUES(39,'0066','Amebic skin ulceration');
INSERT INTO icd9 VALUES(40,'0068','Amebic infection of other sites');
INSERT INTO icd9 VALUES(41,'0069','Amebiasis, unspecified');
INSERT INTO icd9 VALUES(42,'0070','Balantidiasis');
INSERT INTO icd9 VALUES(43,'0071','Giardiasis');
INSERT INTO icd9 VALUES(44,'0072','Coccidiosis');
INSERT INTO icd9 VALUES(45,'0073','Intestinal trichomoniasis');
INSERT INTO icd9 VALUES(46,'0074','Cryptosporidiosis');
INSERT INTO icd9 VALUES(47,'0075','Cyclosporiasis');
INSERT INTO icd9 VALUES(48,'0078','Other specified protozoal intestinal diseases');
INSERT INTO icd9 VALUES(49,'0079','Unspecified protozoal intestinal disease');
INSERT INTO icd9 VALUES(50,'00800','Intestinal infection due to E. coli, unspecified');
INSERT INTO icd9 VALUES(51,'00801','Intestinal infection due to enteropathogenic E. coli');
INSERT INTO icd9 VALUES(52,'00802','Intestinal infection due to enterotoxigenic E. coli');
INSERT INTO icd9 VALUES(53,'00803','Intestinal infection due to enteroinvasive E. coli');
INSERT INTO icd9 VALUES(54,'00804','Intestinal infection due to enterohemorrhagic E. coli');
INSERT INTO icd9 VALUES(55,'00809','Intestinal infection due to other intestinal E. coli infections');
INSERT INTO icd9 VALUES(56,'0081','Intestinal infection due to arizona group of paracolon bacilli');
INSERT INTO icd9 VALUES(57,'0082','Intestinal infection due to aerobacter aerogenes');
INSERT INTO icd9 VALUES(58,'0083','Intestinal infection due to proteus (mirabilis) (morganii)');
INSERT INTO icd9 VALUES(59,'00841','Intestinal infection due to staphylococcus');
INSERT INTO icd9 VALUES(60,'00842','Intestinal infection due to pseudomonas');
INSERT INTO icd9 VALUES(61,'00843','Intestinal infection due to campylobacter');
INSERT INTO icd9 VALUES(62,'00844','Intestinal infection due to yersinia enterocolitica');
INSERT INTO icd9 VALUES(63,'00845','Intestinal infection due to Clostridium difficile');
INSERT INTO icd9 VALUES(64,'00846','Intestinal infection due to other anaerobes');
INSERT INTO icd9 VALUES(65,'00847','Intestinal infection due to other gram-negative bacteria');
INSERT INTO icd9 VALUES(66,'00849','Intestinal infection due to other organisms');
INSERT INTO icd9 VALUES(67,'0085','Bacterial enteritis, unspecified');
INSERT INTO icd9 VALUES(68,'00861','Enteritis due to rotavirus');
INSERT INTO icd9 VALUES(69,'00862','Enteritis due to adenovirus');
INSERT INTO icd9 VALUES(70,'00863','Enteritis due to norwalk virus');
INSERT INTO icd9 VALUES(71,'00864','Enteritis due to other small round viruses [SRV''s]');
INSERT INTO icd9 VALUES(72,'00865','Enteritis due to calicivirus');
INSERT INTO icd9 VALUES(73,'00866','Enteritis due to astrovirus');
INSERT INTO icd9 VALUES(74,'00867','Enteritis due to enterovirus nec');
INSERT INTO icd9 VALUES(75,'00869','Enteritis due to other viral enteritis');
INSERT INTO icd9 VALUES(76,'0088','Intestinal infection due to other organism, not elsewhere classified');
INSERT INTO icd9 VALUES(77,'0090','Infectious colitis, enteritis, and gastroenteritis');
INSERT INTO icd9 VALUES(78,'0091','Colitis, enteritis, and gastroenteritis of presumed infectious origin');
INSERT INTO icd9 VALUES(79,'0092','Infectious diarrhea');
INSERT INTO icd9 VALUES(80,'0093','Diarrhea of presumed infectious origin');
INSERT INTO icd9 VALUES(81,'01000','Primary tuberculous infection, unspecified');
INSERT INTO icd9 VALUES(82,'01001','Primary tuberculous infection, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(83,'01002','Primary tuberculous infection, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(84,'01003','Primary tuberculous infection, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(85,'01004','Primary tuberculous infection, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(86,'01005','Primary tuberculous infection, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(87,'01006','Primary tuberculous infection, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(88,'01010','Tuberculous pleurisy in primary progressive tuberculosis, unspecified');
INSERT INTO icd9 VALUES(89,'01011','Tuberculous pleurisy in primary progressive tuberculosis, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(90,'01012','Tuberculous pleurisy in primary progressive tuberculosis, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(91,'01013','Tuberculous pleurisy in primary progressive tuberculosis, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(92,'01014','Tuberculous pleurisy in primary progressive tuberculosis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(93,'01015','Tuberculous pleurisy in primary progressive tuberculosis, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(94,'01016','Tuberculous pleurisy in primary progressive tuberculosis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(95,'01080','Other primary progressive tuberculosis, unspecified');
INSERT INTO icd9 VALUES(96,'01081','Other primary progressive tuberculosis, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(97,'01082','Other primary progressive tuberculosis, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(98,'01083','Other primary progressive tuberculosis, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(99,'01084','Other primary progressive tuberculosis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(100,'01085','Other primary progressive tuberculosis, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(101,'01086','Other primary progressive tuberculosis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(102,'01090','Primary tuberculous infection, unspecified, unspecified');
INSERT INTO icd9 VALUES(103,'01091','Primary tuberculous infection, unspecified, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(104,'01092','Primary tuberculous infection, unspecified, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(105,'01093','Primary tuberculous infection, unspecified, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(106,'01094','Primary tuberculous infection, unspecified, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(107,'01095','Primary tuberculous infection, unspecified, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(108,'01096','Primary tuberculous infection, unspecified, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(109,'01100','Tuberculosis of lung, infiltrative, unspecified');
INSERT INTO icd9 VALUES(110,'01101','Tuberculosis of lung, infiltrative, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(111,'01102','Tuberculosis of lung, infiltrative, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(112,'01103','Tuberculosis of lung, infiltrative, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(113,'01104','Tuberculosis of lung, infiltrative, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(114,'01105','Tuberculosis of lung, infiltrative, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(115,'01106','Tuberculosis of lung, infiltrative, tubercle bacilli not found bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(116,'01110','Tuberculosis of lung, nodular, unspecified');
INSERT INTO icd9 VALUES(117,'01111','Tuberculosis of lung, nodular, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(118,'01112','Tuberculosis of lung, nodular, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(119,'01113','Tuberculosis of lung, nodular, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(120,'01114','Tuberculosis of lung, nodular, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(121,'01115','Tuberculosis of lung, nodular, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(122,'01116','Tuberculosis of lung, nodular, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(123,'01120','Tuberculosis of lung with cavitation, unspecified');
INSERT INTO icd9 VALUES(124,'01121','Tuberculosis of lung with cavitation, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(125,'01122','Tuberculosis of lung with cavitation, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(126,'01123','Tuberculosis of lung with cavitation, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(127,'01124','Tuberculosis of lung with cavitation, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(128,'01125','Tuberculosis of lung with cavitation, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(129,'01126','Tuberculosis of lung with cavitation, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(130,'01130','Tuberculosis of bronchus, unspecified');
INSERT INTO icd9 VALUES(131,'01131','Tuberculosis of bronchus, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(132,'01132','Tuberculosis of bronchus, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(133,'01133','Tuberculosis of bronchus, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(134,'01134','Tuberculosis of bronchus, tubercle bacilli not found (in sputum) by microscopy, but found in bacterial culture');
INSERT INTO icd9 VALUES(135,'01135','Tuberculosis of bronchus, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(136,'01136','Tuberculosis of bronchus, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(137,'01140','Tuberculous fibrosis of lung, unspecified');
INSERT INTO icd9 VALUES(138,'01141','Tuberculous fibrosis of lung, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(139,'01142','Tuberculous fibrosis of lung, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(140,'01143','Tuberculous fibrosis of lung, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(141,'01144','Tuberculous fibrosis of lung, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(142,'01145','Tuberculous fibrosis of lung, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(143,'01146','Tuberculous fibrosis of lung, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(144,'01150','Tuberculous bronchiectasis, unspecified');
INSERT INTO icd9 VALUES(145,'01151','Tuberculous bronchiectasis, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(146,'01152','Tuberculous bronchiectasis, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(147,'01153','Tuberculous bronchiectasis, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(148,'01154','Tuberculous bronchiectasis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(149,'01155','Tuberculous bronchiectasis, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(150,'01156','Tuberculous bronchiectasis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(151,'01160','Tuberculous pneumonia [any form], unspecified');
INSERT INTO icd9 VALUES(152,'01161','Tuberculous pneumonia [any form], bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(153,'01162','Tuberculous pneumonia [any form], bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(154,'01163','Tuberculous pneumonia [any form], tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(155,'01164','Tuberculous pneumonia [any form], tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(156,'01165','Tuberculous pneumonia [any form], tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(157,'01166','Tuberculous pneumonia [any form], tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(158,'01170','Tuberculous pneumothorax, unspecified');
INSERT INTO icd9 VALUES(159,'01171','Tuberculous pneumothorax, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(160,'01172','Tuberculous pneumothorax, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(161,'01173','Tuberculous pneumothorax, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(162,'01174','Tuberculous pneumothorax, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(163,'01175','Tuberculous pneumothorax, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(164,'01176','Tuberculous pneumothorax, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(165,'01180','Other specified pulmonary tuberculosis, unspecified');
INSERT INTO icd9 VALUES(166,'01181','Other specified pulmonary tuberculosis, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(167,'01182','Other specified pulmonary tuberculosis, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(168,'01183','Other specified pulmonary tuberculosis, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(169,'01184','Other specified pulmonary tuberculosis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(170,'01185','Other specified pulmonary tuberculosis, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(171,'01186','Other specified pulmonary tuberculosis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(172,'01190','Pulmonary tuberculosis, unspecified, unspecified');
INSERT INTO icd9 VALUES(173,'01191','Pulmonary tuberculosis, unspecified, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(174,'01192','Pulmonary tuberculosis, unspecified, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(175,'01193','Pulmonary tuberculosis, unspecified, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(176,'01194','Pulmonary tuberculosis, unspecified, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(177,'01195','Pulmonary tuberculosis, unspecified, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(178,'01196','Pulmonary tuberculosis, unspecified, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(179,'01200','Tuberculous pleurisy, unspecified');
INSERT INTO icd9 VALUES(180,'01201','Tuberculous pleurisy, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(181,'01202','Tuberculous pleurisy, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(182,'01203','Tuberculous pleurisy, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(183,'01204','Tuberculous pleurisy, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(184,'01205','Tuberculous pleurisy, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(185,'01206','Tuberculous pleurisy, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(186,'01210','Tuberculosis of intrathoracic lymph nodes, unspecified');
INSERT INTO icd9 VALUES(187,'01211','Tuberculosis of intrathoracic lymph nodes, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(188,'01212','Tuberculosis of intrathoracic lymph nodes, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(189,'01213','Tuberculosis of intrathoracic lymph nodes, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(190,'01214','Tuberculosis of intrathoracic lymph nodes, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(191,'01215','Tuberculosis of intrathoracic lymph nodes, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(192,'01216','Tuberculosis of intrathoracic lymph nodes, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(193,'01220','Isolated tracheal or bronchial tuberculosis, unspecified');
INSERT INTO icd9 VALUES(194,'01221','Isolated tracheal or bronchial tuberculosis, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(195,'01222','Isolated tracheal or bronchial tuberculosis, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(196,'01223','Isolated tracheal or bronchial tuberculosis, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(197,'01224','Isolated tracheal or bronchial tuberculosis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(198,'01225','Isolated tracheal or bronchial tuberculosis, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(199,'01226','Isolated tracheal or bronchial tuberculosis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
INSERT INTO icd9 VALUES(200,'01230','Tuberculous laryngitis, unspecified');
INSERT INTO icd9 VALUES(201,'01231','Tuberculous laryngitis, bacteriological or histological examination not done');
INSERT INTO icd9 VALUES(202,'01232','Tuberculous laryngitis, bacteriological or histological examination unknown (at present)');
INSERT INTO icd9 VALUES(203,'01233','Tuberculous laryngitis, tubercle bacilli found (in sputum) by microscopy');
INSERT INTO icd9 VALUES(204,'01234','Tuberculous laryngitis, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture');
INSERT INTO icd9 VALUES(205,'01235','Tuberculous laryngitis, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically');
INSERT INTO icd9 VALUES(206,'01236','Tuberculous laryngitis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]');
