CREATE INDEX icd9_idx ON icd9(icd9_code);
CREATE INDEX icd10_idx ON icd10(icd10_code);
CREATE INDEX icd9gem_idx1 ON icd9_gem(icd9_code);
CREATE INDEX icd9gem_idx2 ON icd9_gem(icd10_code);
CREATE INDEX icd10gem_idx1 ON icd10_gem(icd9_code);
CREATE INDEX icd10gem_idx2 ON icd10_gem(icd10_code);
CREATE UNIQUE INDEX icd9_folder_idx ON icd9_folder(name);
CREATE UNIQUE INDEX icd9_folderitem_idx ON icd9_folderitem(folder_id,icd9_id);
CREATE UNIQUE INDEX icd10_folder_idx ON icd10_folder(name);
CREATE UNIQUE INDEX icd10_folderitem_idx ON icd10_folderitem(folder_id,icd10_id);
